id: 387a6a165be1417eb5526a35afa82dac

name: Git Versions

description: A

instructionFile: instructions.md

gleanSearchConfig: {}

model:
  name: GPT_5_6_LUNA_MS
  mode: ADVANCED
  autoUpgrade: true

trigger:
  type: CHAT_MESSAGE

icon:
  backgroundColor: var(--theme-brand-light-blue-50)
  color: '#333'
  iconType: GLYPH
  name: rocket-2
