id: e953e947e23b4ae1bdf5166b74a82087

name: Git Versions

instructionFile: instructions.md

gleanSearchConfig: {}

model:
  name: GPT_5_6_LUNA_MS
  mode: ADVANCED
  autoUpgrade: true

trigger:
  type: CHAT_MESSAGE

icon:
  backgroundColor: var(--theme-brand-light-blue-50)
  color: '#333'
  iconType: GLYPH
  name: rocket-2
